#!/usr/bin/env python3
# coding: utf-8

import a2
import socket
import json
HOST = "localhost"
PORT = 8000     

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind((HOST, PORT))
    s.listen()
    #conn is a new socket object usable to send and receive data on the connection
    #address is the address bound to the socket on the other end of the connection.
    conn, addr = s.accept()
    NumJSON = ""
    with conn:
        while True:
            #recieve data in bytes
            data_received = conn.recv(1024)
            if not data_received:
                break
            #convert to string
            decoded_data = data_received.decode("utf-8")
            NumJSON += decoded_data

            if decoded_data.endswith("END\n"):
                JSON_array = a2.main("--sum", NumJSON)
                conn.sendall(json.dumps(JSON_array).encode('utf-8'))
                break
                
        
